<a href="https://colab.research.google.com/github/ACROS-UMBC/UMBC-PHYS640-440/blob/Fall2021/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Computational Physics (PHYS 640)

## A Quick Tutorial of Python Basic Syntax

### By Zhibo Zhang,  Physics Department, UMBC

You can also learn Python basic syntax from the online tutorials listed below 

https://docs.python.org/3.6/tutorial/

http://www.codecademy.com/en/tracks/python

http://www.learnpython.org/

http://www.tutorialspoint.com/python/


## 1) A Quick Start

To start the python programming, type "ipython --pylab" in the a terminal window. You will see something like


There are two basics modes to run use Python, the ***Interactive*** mode and the ***Script*** model. In the Interactive mode, you can simply type some command and then hit "enter" to excute the command yout typed in. 
Let's try the following examples:

In [ ]:
print("Hello PHYS220!")

Hello PHYS220!


In [ ]:
print("hello 1,2,3")

hello 1,2,3


In [ ]:
print ("hello world")


hello world


In [ ]:
1+3

4

In [ ]:
2+3

5

In [ ]:
a = ['spam', 'eggs', 100.0, 1234]
print(a)
type(a[0])

['spam', 'eggs', 100.0, 1234]


str

Sometimes, you may run into some problems and the python Integrated development environment (IDE) may give you some hint about the problem

In [ ]:
365+"Monday"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In this example, the IDE basiclly tells you that the integral 365 and th string "Monday" are not addable 

### 1.1 Python Identifiers:

A Python identifier is a name used to identify a variable, function, class, module or other object. An identifier starts with a letter A to Z or a to z or an underscore (_) followed by zero or more letters, underscores and digits (0 to 9). 

Python does not allow punctuation characters such as @, $ and % within identifiers. **Python is a case sensitive programming language.** Thus, Manpower and manpower are two different identifiers in Python.

In [ ]:
P=4
p='fg'
print (P,p)

4 fg


**The following list shows the reserved words in Python.** These reserved words may not be used as constant or variable or any other identifier names. All the Python keywords contain lowercase letters only.

In [ ]:
and = 5 ; for = '123'

SyntaxError: invalid syntax (<ipython-input-13-cef3e72e7475>, line 1)

### 1.2 Lines and Indentation:

One of the first caveats programmers encounter when learning Python is the fact that there are no braces to indicate blocks of code for class and function definitions or flow control. Blocks of code are denoted by line indentation, which is rigidly enforced.

The number of spaces in the indentation is variable, but all statements within the block must be indented the same amount. Both blocks in this example are fine:

In [ ]:
a = 5.0
b = 2.0
''''''
if a>=0:
    print ("A is larger than zero")
    print ("Positive")
else: 
    print ("A is smaller than zero")
    print ("negative")

A is larger than zero
Positive


** * **

## 2) Python Variable Types

### 2.1 Assigning Values to Variables:

Python variables do not have to be explicitly declared to reserve memory space. The declaration happens automatically when you assign a value to a variable. The equal sign (=) is used to assign values to variables. The operand to the left of the = operator is the name of the variable and the operand to the right of the = operator is the value stored in the variable. For example:

In [ ]:
counter = 100          # An integer assignment
miles   = 1000.0       # A floating point
name    = "John"       # A string

print (counter)
print (miles)
print (name)

print (type(miles), type(name))

100
1000.0
John
<class 'float'> <class 'str'>


Python allows you to assign a single value to several variables simultaneously. For example:

In [ ]:
a = b = c = 1
print (a,b,c)

b=3.0
print (a,b,c)

1 1 1
1 3.0 1


Here, an integer object is created with the value 1, and all three variables are assigned to the same memory location. You can also assign multiple objects to multiple variables. For example:

In [ ]:
a, b, _ = 1, 2.0,'cat'
print (a,b,c)

1 2.0 cat


In [ ]:
def fx():
    return 6,5,4

a,_,b=fx()
print(a,b)

6 4


You can also assign values to varaible through standard input

In [ ]:
x=input()
print (x), type(x)
x=2
print (x), type(x)

x=float(x)
print (x), type(x)


2
2.0


(None, float)

### 2.2 Standard Data Types:

The data stored in memory can be of many types. For example, a person's age is stored as a numeric value and his or her address is stored as alphanumeric characters. Python has various standard types that are used to define the operations possible on them and the storage method for each of them.

Python has five standard data types: 1) **Numbers** 2) **String** 3) **List** 4) **Tuple** 5) **Dictionary**

#### 2.2.1 Python Numbers:

Number data types store numeric values. They are immutable data types which means that changing the value of a number data type results in a newly allocated object.

Python supports four different numerical types:

1) int (signed integers)

2) long (long integers [can also be represented in octal and hexadecimal])

3) float (floating point real values)

4) complex (complex numbers)

Number objects are created when you assign a value to them. For example:

In [ ]:
x=-2
#y=560L  python 3 gets rid of the "long integer"
y=123456789012345678901234567890
z=35.78        
c=3.0+4.5j #A complex number consists of an ordered pair of real floating-point numbers denoted by a + bj, where a is the real part and b is the imaginary part of the complex number.
print ('x=',x,'y=',y,'z=',z,'c=',c)
print (type(x),type(y),type(z), type(c)) # "type" function shows the data type of a variable

x= -2 y= 123456789012345678901234567890 z= 35.78 c= (3+4.5j)
<class 'int'> <class 'int'> <class 'float'> <class 'complex'>


You can use the constructors int(), long(), float(), and complex() to produce numbers of a specific type.

In [ ]:
import numpy as np
print(float(y)) # convert y from long integer to float
print(np.int(z))# convert z from float to complex
#print float(c.real)# convert real part of c to integer

1.2345678901234568e+29
35


You can check the system-specific parameters of each numerical typics. To do this, you need to use the system library "sys". In the following examples, we check the maximum possible values of floating point and integer number in python:

In [ ]:
import sys # import system library
print('maximum of floating point:',sys.float_info.max) 
print('maximum of integer:',sys.maxsize) 


maximum of floating point: 1.7976931348623157e+308
maximum of integer: 9223372036854775807


#### 2.2.2 Python Strings:

Strings in Python are identified as a contiguous set of characters in between quotation marks. Python allows for either pairs of single or double quotes. Subsets of strings can be taken using the slice operator ( [ ] and [ : ] ) **with indexes starting at 0** in the beginning of the string and working their way from -1 at the end. The plus ( + ) sign is the string concatenation operator and the asterisk ( * ) is the repetition operator. For example:

In [ ]:
str = 'Hello_PHYS2020'


print (str          )# Prints complete string
print (str[0]      ) # Prints first character of the string
print (str[2:5] )    # Prints characters starting from 3rd to 5th
print (str[:2]  )    # Prints  the first two chars
print (str[2:] )     # Prints string starting from 3rd character
print (str[-1::-1])   # Prints 2 chars before the last one
print (str[-3:] )    # Prints the last 3 chars 
print (str * 2 )     # Prints string two times
print (str + "TEST") # Prints concatenated string

Hello_PHYS2020
H
llo
He
llo_PHYS2020
0202SYHP_olleH
020
Hello_PHYS2020Hello_PHYS2020
Hello_PHYS2020TEST


In [ ]:
print(str[::-1])

0202SYHP_olleH


In [ ]:
c=[0,1,2,3,4,5,6,7,8,9]


In [ ]:
print(c[1::2])
print(c[1::2][3])

[1, 3, 5, 7, 9]
7


A few words about indexing conventions of Python string. Let's focus on the following example. First, let's create a simple string 'a'.

In [ ]:
import numpy as np
a= np.arange(10)
a +=100
print (len(a),a)
print (a[0:5])

10 [100 101 102 103 104 105 106 107 108 109]
[100 101 102 103 104]


The most general way to slice 'a' is b=a[**start : stop  : step**]

There are only three things to remember

**start** is the first item that we want (of course) default value is "0" i.e. the first position

**stop** is the <font color='red'>first item that we do **not** want</font> the default value is the last character (i.e., len(a) len() is a function to get the length of a string)

**step**, being positive or negative, defines whether we are moving forwards (from the first position of the string towards its end) or backwards (from the last position of the str towards its start), the default value is 1

Try the following examples:

In [ ]:
print (a[0:10])
print (a[0:len(a):2])# begins with the first char, stops at the last one, every other char

[100 101 102 103 104 105 106 107 108 109]
[100 102 104 106 108]


In [ ]:
a[1::2] # bgins with the 2nd char (remember the index starts with 0), stops at the last one by default, every other char

array([101, 103, 105, 107, 109])

In [ ]:
a[3:8:3] # begins with the 4th char, stops at the 7th char (7), every third char

array([103, 106])

Another thing about indexing is that Python allows **negative** indices. For example, 

In [ ]:
a[-5::2] 

array([105, 107, 109])

In [ ]:
a[-7:-2:2]

array([103, 105, 107])

Evening more confusing is that, using the negative step size, you can make the slicing go backword. For exmple, 

In [ ]:
a[-1:0:-1]

array([109, 108, 107, 106, 105, 104, 103, 102, 101])

### 2.2.3 Python Lists:

Lists are the most versatile of Python's compound data types. A list contains items separated by commas and enclosed within square brackets ([]). To some extent, lists are similar to arrays in C. One difference between them is that all the items belonging to a list can be of different data type.

The values stored in a list can be accessed using the slice operator ( [ ] and [ : ] ) with indexes starting at 0 in the beginning of the list and working their way to end -1. The plus ( + ) sign is the list concatenation operator, and the asterisk ( * ) is the repetition operator. For example:

In [ ]:
list = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
tinylist = [123, 'john']

print (list)          # Prints complete list
print (list[0][1])       # Prints first element of the list
print (list[1:3])     # Prints elements starting from 2nd till 3rd 
print (list[2:])      # Prints elements starting from 3rd element
list[3] = 'cat'
print (tinylist * 2)  # Prints list two times
print (list + tinylist) # Prints concatenated lists

c=[7,6]
[c.append(i) for  i in [3,4,5]]
c.append('f')
c.append('g')
print (c)
print (c[2])

['abcd', 786, 2.23, 'john', 70.2]
b
[786, 2.23]
[2.23, 'john', 70.2]
[123, 'john', 123, 'john']
['abcd', 786, 2.23, 'cat', 70.2, 123, 'john']
[7, 6, 3, 4, 5, 'f', 'g']
3


Note that the list variable uses the same indexing convention as the string variable.For example:

In [ ]:
list[0::2]

['abcd', 2.23, 70.2]

In [ ]:
list[-3:-1]

[2.23, 'cat']

### 2.2.4 Python Tuples:

A tuple is another sequence data type that is similar to the list. A tuple consists of a number of values separated by commas. Unlike lists, however, tuples are enclosed within parentheses.

The main differences between lists and tuples are: Lists are enclosed in brackets ( [ ] ) and their elements and size can be changed, while tuples are enclosed in parentheses ( ( ) ) and cannot be updated, i.e., immutable. Tuples can be thought of as read-only lists. For example:

In [ ]:
tuple = ( 'abcd', 786 , 2.23, 'john', 70.2  )
tinytuple = (123, 'john')

print (tuple          ) # Prints complete list
print (tuple[0]     )   # Prints first element of the list
print (tuple[4:0])      # Prints elements starting from 2nd till 3rd 
print (tuple[2:] )      # Prints elements starting from 3rd element
#tuple[3] = 'cat'
#print (tinytuple * 2)   # Prints list two times
#print (tuple + tinytuple) # Prints concatenated lists

('abcd', 786, 2.23, 'john', 70.2)
abcd
()
(2.23, 'john', 70.2)


Following is invalid with tuple, because we attempted to update a tuple, which is not allowed. Similar case is possible with lists:

In [ ]:
tuple = ( 'abcd', 786 , 2.23, 'john', 70.2  )
for t in tuple:
    print(t)
del tuple

tp = ('a','b','c')
cp=''.join(tp)
print(type(cp))

abcd
786
2.23
john
70.2
<class 'str'>


### 2.2.5 Python Dictionary:

In [ ]:
v=1,2,3,4
print(type(v))

<class 'tuple'>


In [ ]:
dk = {'name':'Zhibo Zhang','age':25,'affiliation':'UMBC'}
print(dk['age'])
season = {'Spring':[3,4,5],'Summer':[6,7,8],'Fall':[9,10,11],'Winter':[12,1,2]}
print(season.keys())
print(season.values())
print(season.items())

25
dict_keys(['Spring', 'Summer', 'Fall', 'Winter'])
dict_values([[3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 1, 2]])
dict_items([('Spring', [3, 4, 5]), ('Summer', [6, 7, 8]), ('Fall', [9, 10, 11]), ('Winter', [12, 1, 2])])


In [ ]:
dk['name'] = ['zhibo','Mike']
dk['age'] = [35, 40]
dk['affiliation'] = ['UMBC','JCET']

In [ ]:
for k,v in season.items():
    print(k,v)

Spring [3, 4, 5]
Summer [6, 7, 8]
Fall [9, 10, 11]
Winter [12, 1, 2]


In [ ]:
dk2 = {'first':[],'second':[],'third':[]}
dk2['first'] = '1'
print(dk2)

{'first': '1', 'second': [], 'third': []}


In [ ]:
print(season['Fall'])
mon = 5
for (k,v) in season.items():
    print(k,v)
    if mon in v:
        print('month',mon, 'is in',k)


[9, 10, 11]
Spring [3, 4, 5]
month 5 is in Spring
Summer [6, 7, 8]
Fall [9, 10, 11]
Winter [12, 1, 2]


Python's dictionaries are kind of hash table type. They work like associative arrays or hashes found in Perl and consist of key-value pairs. A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any arbitrary Python object.

Dictionaries are enclosed by curly braces ( { } ) and values can be assigned and accessed using square braces ( [] ). For example:

In [ ]:
dict = {}
dict['one'] = "This is one"
dict[2]     = "This is two"
dict['three'] = 'this is three'
print(dict['one'])
tinydict = {'name': 'john','code':6734, 'dept': 'sales'}
print(tinydict['name'])
print(tinydict.keys())
print(tinydict.values())
print(tinydict.items())

for (k,v) in tinydict.items():
    print(k,v)


This is one
john
dict_keys(['name', 'code', 'dept'])
dict_values(['john', 6734, 'sales'])
dict_items([('name', 'john'), ('code', 6734), ('dept', 'sales')])
name john
code 6734
dept sales


### 2.2.6 Data Type Conversion:

Sometimes, you may need to perform conversions between the built-in types. To convert between types, you simply use the type name as a function.

There are several built-in functions to perform conversion from one data type to another. These functions return a new object representing the converted value.


**int(x [,base])**

Converts x to an integer. base specifies the base if x is a string.

**long(x [,base] )**

Converts x to a long integer. base specifies the base if x is a string.

**float(x)**

Converts x to a floating-point number.

**complex(real [,imag])**

Creates a complex number.

**str(x)**

Converts object x to a string representation.

**tuple(s)**

Converts s to a tuple.

**list(s)**

Converts s to a list.

**dict(d)**

Creates a dictionary. d must be a sequence of (key,value) tuples.

** * **

## 3) Python Basic Operators

Python language supports the following types of operators.

**Arithmetic Operators**

**Assignment Operators**


**Comparison (i.e., Relational) Operators**

**Logical Operators**

**Bitwise Operators**

**Membership Operators**

**Identity Operators**

Let's have an overview  on the first three


### 3.1 Python Arithmetic Operators:

<font color='red'> + </font> : Addition - Adds values on either side of the operator

<font color='red'> - </font>  : Subtraction - Subtracts right hand operand from left hand operand

<font color='red'> * </font> : Multiplication - Multiplies values on either side of the operator

<font color='red'> / </font> : Division - Divides left hand operand by right hand operand

In [ ]:
from __future__ import division
7/3

2.3333333333333335

<font color='red'> % </font> : Modulus - Divides left hand operand by right hand operand and returns remainder

In [ ]:
7%3

1

<font color='red'> **  </font> : Exponent - Performs exponential (power) calculation on operators

<font color='red'>// </font> : Floor Division - The division of operands where the result is the quotient in which the digits after the decimal point are removed.

In [ ]:
3**2

9

In [ ]:
6.3//3

2.0

In [ ]:
#from __future__ import division print_function
a = 21
b = 10
c = 0

c = a + b
print ("Line 1 - Value of c is ", c)

c = a - b
print ("Line 2 - Value of c is ", c) 

c = a * b
print ("Line 3 - Value of c is ", c )

c = a / b
print ("Line 4 - Value of c is ", c )

c = a % b
print ("Line 5 - Value of c is ", c)

a = 2
b = 3
c = a**b 
print ("Line 6 - Value of c is ", c)

a = 13
b = 6
c = a//b 
print("Line 7 - Value of c is ", c)

Line 1 - Value of c is  31
Line 2 - Value of c is  11
Line 3 - Value of c is  210
Line 4 - Value of c is  2.1
Line 5 - Value of c is  1
Line 6 - Value of c is  8
Line 7 - Value of c is  2


 **Be careful** about the 'division'. In Python 2.x, the operator '/'  is **integer division** if inputs are integers. 
See the examples below:

In [ ]:
print ("5/3=" , 5/3 )
print ("5.0/3.0 = ",  5.0/3.0)
a,b=7,3
print (a,b, a/b)

3+80.343

5/3= 1.6666666666666667
5.0/3.0 =  1.6666666666666667
7 3 2.3333333333333335


83.343

### 3.2 Python Assignment Operators:

<font color='red'>= </font>     :Simple assignment operator <br>       Assigns values from right side operands to left side operand <br>      c = a + b will assigne value of a + b into c  <br> <br>
<font color='red'>+=</font>	:Add AND assignment operator <br>  It adds right operand to the left operand and assign the result to left operand <br>	 c += a is equivalent to c = c + a <br><br>
<font color='red'>-=</font>	 :Subtract AND assignment operator <br> It subtracts right operand from the left operand and assign the result to left operand	<br>  c -= a is equivalent to c = c - a <br><br>
<font color='red'>**=</font>	:Multiply AND assignment operator <br>It multiplies right operand with the left operand and assign the result to left operand <br> c *= a is equivalent to c = c * a <br><br>
<font color='red'>/=</font>	:Divide AND assignment operator <br> It divides left operand with the right operand and assign the result to left operand <br>	 c /= a is equivalent to c = c / a <br><br>
<font color='red'>%=</font>	:Modulus AND assignment operator <br> It takes modulus using two operands and assign the result to left operand	<br> c %= a is equivalent to c = c % a <br><br>
<font color='red'>****=</font> :Exponent AND assignment operator <br> Performs exponential (power) calculation on operators and assign value to the left operand<br>	 c **= a is equivalent to c = c ** a <br><br>
<font color='red'>//=</font>	:Floor Dividion and assigns a value <br> Performs floor division on operators and assign value to the left operand	<br>  c //= a is equivalent to c = c // a <br>


In [ ]:
a = 2
b = 3
c = 0

c = a + b
print ("Line 1 - Value of c is ", c)

c += a 

print ("Line 2 - Value of c is ", c)

c *= a
print ("Line 3 - Value of c is ", c) 

c /= a 
print ("Line 4 - Value of c is ", c) 

c  = 45
c %= a
print ("Line 5 - Value of c is ", c)

c = 2
a = 3
c **= a
print ("Line 6 - Value of c is ", c)

c = 8.7
a = 3
c //= a
print ("Line 7 - Value of c is ", c)

Line 1 - Value of c is  5
Line 2 - Value of c is  7
Line 3 - Value of c is  14
Line 4 - Value of c is  7.0
Line 5 - Value of c is  1
Line 6 - Value of c is  8
Line 7 - Value of c is  2.0


### 3.3 Python Comparison Operators

Asuming a=10, b=20 <br><br>
<font color='red'>==</font>	 :Checks if the value of two operands are equal or not, if yes then condition becomes true. <br>	 (a == b) is not true. <br> <br>
<font color='red'>!=</font>		 :Checks if the value of two operands are equal or not, if values are not equal then condition becomes true. <br>	 (a != b) is true. <br> <br>

 <font color='red'>></font>		 :Checks if the value of left operand is greater than the value of right operand, if yes then condition becomes true. <br>	 (a > b) is not true. <br> <br>
 <font color='red'><</font>		 :Checks if the value of left operand is less than the value of right operand, if yes then condition becomes true. <br>	 (a < b) is true. <br> <br>
 <font color='red'>>=</font>		 :Checks if the value of left operand is greater than or equal to the value of right operand, if yes then condition becomes true. <br>  (a >= b) is not true. <br> <br>
  <font color='red'><=</font>		 :Checks if the value of left operand is less than or equal to the value of right operand, if yes then condition becomes true.	<br>  (a <= b) is true. <br>

In [ ]:
a = 21
b = 10
c = 0

if ( a == b ):
   print ("Line 1 - a is equal to b")
else:
   print ("Line 1 - a is not equal to b")

if ( a != b ):
   print ("Line 2 - a is not equal to b")
else:
   print ("Line 2 - a is equal to b")

# if ( a <> b ):
#     print ("Line 3 - a is not equal to b")
# else:
#     print ("Line 3 - a is equal to b")

if ( a < b ):
   print ("Line 4 - a is less than b" )
else:
   print ("Line 4 - a is not less than b")

if ( a > b ):
   print ("Line 5 - a is greater than b")
else:
   print ("Line 5 - a is not greater than b")

a = 5;
b = 20;
if ( a <= b ):
   print ("Line 6 - a is either less than or equal to  b")
else:
   print ("Line 6 - a is neither less than nor equal to  b")

if ( b >= a ):
   print ("Line 7 - b is either greater than  or equal to b")
else:
   print ("Line 7 - b is neither greater than  nor equal to b")

Line 1 - a is not equal to b
Line 2 - a is not equal to b
Line 4 - a is not less than b
Line 5 - a is greater than b
Line 6 - a is either less than or equal to  b
Line 7 - b is either greater than  or equal to b


### 3.4 Python Logical Operators:

assuming a=10, b=20

<font color='red'>and</font>	 :Called Logical AND operator. If both the operands are true then then condition becomes true.<br>  (a and b) is true.<br> <br> 
<font color='red'>or</font>	:Called Logical OR Operator. If any of the two operands are non zero then then condition becomes true.<br> 	 (a or b) is true.<br> <br> 
<font color='red'>not</font>	:Called Logical NOT Operator. Use to reverses the logical state of its operand. If a condition is true then Logical NOT operator will make false.	<br>  not(a and b) is false.

In [ ]:
a = False
b = True
c = 0

if ( a and b ):
    print ("Line 1 - a and b are both true")
else:
    print ("Line 1 - Either a is not true or b is not true")

if ( a or b ):
    print ("Line 2 - Either a is true or b is true or both are true")
else:
    print ("Line 2 - Neither a is true nor b is true")

if not a:
    print ("Line 3 - a is False")
else:
    print ("Line 3 - a is Ttrue")

if not ( a and b ):
    print ("Line 4 - a and b are not both true")
else:
    print ("Line 4 - a and b are both true")



Line 1 - Either a is not true or b is not true
Line 2 - Either a is true or b is true or both are true
Line 3 - a is False
Line 4 - a and b are not both true


## 4) Python Decision Making

Decision making structures require that the programmer specify one or more conditions to be evaluated or tested by the program, along with a statement or statements to be executed if the condition is determined to be true, and optionally, other statements to be executed if the condition is determined to be false.

Python programming language assumes any **non-zero** and **non-null** values as **true**, and if it is either **zero or null**, then it is assumed as **false** value.

### 4.1 "if" statement

4.1.1 ***if*** Syntax: <br>
if expression: <br> 
<pre>statement(s)</pre> 

In [ ]:
# var1 = 300
# var2 = 200
# if (var1>=var2): # do not forget the colon ":"
#     print "1 - Got a true expression value"
#     print var1

# if var1<=var2: print 'hi'

var2 = 0
a= 5>8
if a :
    print ("2 - Got a true expression value")
    print (var2)
    print ("Good bye!")
    print ('end')

4.1.2 ***if... else...*** Syntax: <br>
    if expression: <br>
<pre>statement(s) </pre><br>
else:
<pre> statement(s) </pre>
       

In [ ]:
var1 = 10
var2 = 6
if var1>100:
    print ("1 - Got a true expression value")
    print (var1)
    if var2 == 6:
        print ('var2=',var2)
else:
    print ("1 - Got a false expression value")
    print (var1)

# var2 = 0
# if var2:
#    print "2 - Got a true expression value"
#    print var2
# else:
#    print "2 - Got a false expression value"
#    print var2

# print "Good bye!"

1 - Got a false expression value
10


4.1.2 ***if... elif... else...*** Syntax: <br>

if expression1:
<pre>statement(s)</pre>
<pre>if expression2:</pre>
<pre><pre>statement(s)</pre></pre>
  <pre>elif expression3:</pre>
     <pre> <pre>statement(s)</pre></pre>
    <pre>else</pre>
     <pre> statement(s)</pre>
elif expression4:
   <pre>statement(s)</pre>
else:
<pre>statement(s)</pre>

In [ ]:
var = 600
if var < 200:
    print ("Expression value is less than 200")
    if var == 150: print ("Which is 150")
    if var == 100: print ("Which is 100")
    if var == 50:   print ("Which is 50")
    if var == 6000: print ("which is 6000")
elif (var < 2000):
    print ("Expression value is larger than 200 and smaller than 2000")
else:
    print ("Could not find true expression")
    print ("Good bye!")

Expression value is larger than 200 and smaller than 2000


## 5) Python Loops

There may be a situation when you need to execute a block of code several number of times. In general, statements are executed sequentially: The first statement in a function is executed first, followed by the second, and so on.


Python programming language provides following types of loops to handle looping requirements. Click the following links to check their detail.

### 5.1  "while" loop

A while loop statement in Python programming language repeatedly executes a target statement as long as a given condition is true.

**Syntax:** <br>
    **while** expression:
<pre>statement(s)</pre>

In [ ]:
# while loop example:
count = 0
while count < 9:
    print ('The count is:', count)
    count += 2

print ("Good bye!")

The count is: 0
The count is: 2
The count is: 4
The count is: 6
The count is: 8
Good bye!


Python supports to have an **else** statement associated with a loop statement.

If the **else** statement is used with a while loop, the **else** statement is executed when the condition becomes false.

The following example illustrates the combination of an else statement with a while statement that prints a number as long as it is less than 5, otherwise else statement gets executed.

In [ ]:
count = 10
while count < 5:
    print (count, " is  less than 5")
    count += 1
else:
    print (count, " is not less than 5 ... loop finished")

print ("after the while... else loop")

10  is not less than 5 ... loop finished
after the while... else loop


In [ ]:
count = 0
while count < 5:
    count += 1
    if count>=3:    
        print('we got a 3')
        break
    print (count, " is  less than 5")
else:
    print (count, " is not less than 5")
    
print('while loop finished')

1  is  less than 5
2  is  less than 5
we got a 3
while loop finished


###  5.2 "for" loop

The for loop in Python has the ability to iterate over the items of any sequence, such as a list or a string.

**Syntax:** <br>
**for** iterating_var in sequence:
<pre>statements(s)</pre>


In [ ]:
# for letter in 'Python':     # First Example
#    print 'Current Letter :', letter

fruits = ['banana', 'apple',  'mango']
for f in fruits:        # Second Example
    print ('Current fruit :', f)
print (fruits)
# print "Good bye!"

Current fruit : banana
Current fruit : apple
Current fruit : mango
['banana', 'apple', 'mango']


In [ ]:
print (range(3))
fruits = ['banana', 'apple',  'mango']
for index in range(3):    
    print ('Current fruit #:', index,  fruits[index])

# print "Good bye!"

range(0, 3)
Current fruit #: 0 banana
Current fruit #: 1 apple
Current fruit #: 2 mango


**The else Statement Used with Loops**
Python supports to have an **else** statement associated with a loop statement.

If the **else** statement is used with a **for** loop, the **else** statement is executed when the loop has exhausted iterating the list.

The following example illustrates the combination of an else statement with a for statement that searches for prime numbers from 10 through 20.


In [ ]:
for num in range(10,20):  #to iterate between 10 to 20
    for i in range(2,num): #to iterate on the factors of the number
        #print 'current i',i
        if num%i == 0:      #to determine the first factor
            j=num//i          #to calculate the second factor
            print ('%d equals %d * %d' % (num,i,j))
            break #to move to the next number, the #first FOR
    else:                  # else part of the loop
        print (num, 'is a prime number')

10 equals 2 * 5
11 is a prime number
12 equals 2 * 6
13 is a prime number
14 equals 2 * 7
15 equals 3 * 5
16 equals 2 * 8
17 is a prime number
18 equals 2 * 9
19 is a prime number


### 5.3 Loop Control Statements: break and continue

**break** statement: Terminates the loop statement and transfers execution to the statement immediately following the loop.

In [ ]:
for letter in 'Python':     # First Example
    if letter == 'h':
        continue
    print ('Current Letter :', letter)
  
# var = 10                    # Second Example
# while var > 0:              
#     print 'Current variable value :', var
#     var -= 1
#     if var == 5:
#         break

print ("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
Current Letter : o
Current Letter : n
Good bye!


**continue** statement:Causes the loop to skip the remainder of its body and immediately retest its condition prior to reiterating.

In [ ]:
for letter in 'Python':     # First Example
    if letter == 'h':
        continue
    print ('Current Letter :', letter)

# var = 10                    # Second Example
# while var > 0:              
#     var = var -1
#     if var == 5:
#         continue
#     print 'Current variable value :', var
print ("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
Current Letter : o
Current Letter : n
Good bye!
